### ISSUE TITLE
IsPwnedPassword rule in v1.2 is broken

### ISSUE THREAD

**Issue by tommy-bolger** [nickurt/laravel-pwned-passwords#1]
In your documentation you have this code snippet to show how to use this package as a validation rule:

```
public function rules()
{
    return [
        'password' => ['required', new \nickurt\PwnedPasswords\Rules\IsPwnedPassword(20)]
    ];
}
```

However if I do that I get this error in the latest stable release (1.2):

```
Symfony\Component\Debug\Exception\FatalThrowableError: Too few arguments to function nickurt\PwnedPasswords\Rules\IsPwnedPassword::__construct(), 0 passed in /var/www/app/Components/CommonApiValidationRules.php on line 101 and at least 1 expected in file /var/www/vendor/nickurt/laravel-pwned-passwords/src/Rules/IsPwnedPassword.php on line 27
```

if I look at the `IsPwnedPassword.php` class I see that it's requiring a password as the first argument with frequency being the second. When I compare it to your master I see that you have already fixed this file and I would imagine it works.

I am including this package via composer and am not able to include the latest dev master version of this package. Would you be able to create a new release or backport this fix to 1.2? That would be very much appreciated.

Thank you for your time! This is a very nice modern package.

**Comment by nickurt** [comment]
hi @tommy-bolger,

Just tagged dev-master as 1.3 and confirmed the examples works ..

```php
namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class PwnedPasswordRequest extends FormRequest
{
    //

    public function rules()
    {
        return [
            'password' => ['required', new \nickurt\PwnedPasswords\Rules\IsPwnedPassword(20)]
        ];
    }
}

Route::get('/', function (\App\Http\Requests\PwnedPasswordRequest $request) {
    dd($request->validated());
});
```

```php
Route::get('/', function () {
    $validator = validator()->make(request()->all(), ['password' => ['required', new \nickurt\PwnedPasswords\Rules\IsPwnedPassword(20)]]);

    dd($validator->passes());
});
```
