### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by RyanTheAllmighty** [nickurt/laravel-pwned-passwords#2]
Hi 👋 

Laravel 8 has arrived this week, and when upgrading my application, noticed this package wasn't updated yet.

Are you currently looking at doing that? Would you like a pull request to add support?

Doesn't look like there's any significant changes, just a composer.json update to upgrade the dependency versions for `laravel/framework` and `guzzlehttp/guzzle`

Thanks

**Comment by nickurt** [comment]
Hi, a pull request with updated github actions test for Laravel 8 is enough
